https://github.com/digicope/ai_basic

## numpy

- list : linked list(불연속), 동작 속도가 느리다. comma구분, 서로 다른 자료형 사용가능
- ndarray(배열) : 연속된 메모리 구조, 빠르다,  공백으로 구분, 한 가지 type만

https://scipy.org/

In [2]:
list1 = [1,2,3,4,5,'hello']
type(list1)

list

In [3]:
import numpy as np
np.sctypeDict.keys()

# numpy 의 dtype 객체의 종류: 대소문자 모두 사용가능

C:\Users\Gyu\Anaconda3\envs\py37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Gyu\Anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Gyu\Anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [4]:
a= np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


- <U32 : U : 유니코드, 32 : 최대문자 32byte
- euc-kr, cp949(ms949) : 완성형 한글2바이트, 영문 1바이트, windows
- utf-8 : 조합형, 한글 3byte, 영문 1byte, linux

<br>
2차원 배열의 Shape : 행(row,가로,수직,axis = 0) 과 열(column,세로,수평,axis =1)


In [6]:
!jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


c:\users\gyu\anaconda3\envs\py37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\gyu\anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
c:\users\gyu\anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


In [7]:
!jt -t oceans16

c:\users\gyu\anaconda3\envs\py37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\gyu\anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
c:\users\gyu\anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


### indexing, slicing

In [8]:
d = np.arange(12)
print(d,d.shape)
print(d[0],d[1],d[2],d[3],d[11],d[-1])
print(d[2:8],d[:],d[:-1])
print(d[::2],d[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1 2 3 11 11
[2 3 4 5 6 7] [ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10] [11 10  9  8  7  6  5  4  3  2  1  0]


In [9]:
d = np.arange(12).reshape(3,4)

print(d[0])     # [0 1 2 3]
print(d[0,:])   # [0 1 2 3]

print(d[:,:-1])   # (3,3), 마지막 열을 제외
print(d[::2,::2]) # (2,2)

d[::2,::2] = 30
print(d)

d[:,:] = -1      # 전체 요소를 한번에 변경할 수 있다
print(d)

[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]
[[30  1 30  3]
 [ 4  5  6  7]
 [30  9 30 11]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [10]:
d = np.arange(12).reshape(2,2,3)
print(d,d.shape)

print(d[:,:-1,:-1]) # (2,1,2)
print(d[:,1:,1:])   # (2,1,2)
print(d[:,:,-1])    # (2,2)
print(d[:,-1,-1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


**boolean indexing** : 조건 필터

In [11]:
a = np.array([1,2,3,4,5,6])
boolean_index = np.array([True,False,True,False,True,False])
print(a[boolean_index])
print(a[ a < a.mean()]) 

[1 3 5]
[1 2 3]


**fancy 인덱싱** : 리스트나 배열로 임의의 집합을 지정하여 인덱싱

In [13]:
a = np.arange(10,100,10).reshape(3,3)
print(a[[0,2],[0,1]])

[10 80]


In [14]:
d = np.arange(12).reshape(3,4)
f = d.flatten()
print(f)
d.flat = 0
print(d,d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)


In [15]:
a = np.arange(12).reshape(3,4)

print(a.sum())   # 배열 전체의 합
print(a.sum(axis=None))   # 배열 전체의 합

print(a.sum(axis=0))  # 수직 방향의 합
print(a.sum(axis=1))  # 수평 방향의 합
print(a.sum(axis=-1))  # 마지막 축 방향의 합

66
66
[12 15 18 21]
[ 6 22 38]
[ 6 22 38]


In [17]:
a = np.array([9,2,8,3,1,4,5,6])

r = np.sort(a)[::-1] # 내림 차순: 오름 차순 정렬후 순서를 거꾸로 변경 
print(r)

[9 8 6 5 4 3 2 1]


In [18]:
# argsort() 함수 : sort된 후 해당 값의 인덱스(원본기준)를 반환
a = np.array([9,2,8,3,1,4,5,6])

sort_index = np.argsort(a)  # 오름차순
print(sort_index)   
print(a[sort_index])

sort_index = np.argsort(-1*a) # 내림차순

print(sort_index)   
print(a[sort_index])

[4 1 3 5 6 7 2 0]
[1 2 3 4 5 6 8 9]
[0 2 7 6 5 3 1 4]
[9 8 6 5 4 3 2 1]


In [2]:
import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])
print(A*B)   # element-wise 곱셈

dot_product = np.dot(A,B)  # 내적 곱셈
print(dot_product)

C:\Users\Gyu\Anaconda3\envs\py37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Gyu\Anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Gyu\Anaconda3\envs\py37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


[ 4 10 18]
32


In [3]:
A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(3,2)
print(np.matmul(A,B))
print(np.dot(A,B))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [4]:
A = np.mat("1 2 3;4 5 6")
B = np.mat("7 8;9 10;11 12")
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [5]:
A = np.mat("1 -2 1;0 2 -8;-4 5 9")
print("A:",A)
b = np.array([0,8,-9])
print(b)

A: [[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
[ 0  8 -9]


In [6]:
x = np.linalg.solve(A,b)
print('Solution:',x)
print('Check\n',np.dot(A,x))

Solution: [29. 16.  3.]
Check
 [[ 0.  8. -9.]]
